#!/bin/bash
# Run apt update and upgrade at the same time


exit_error() {
    # print errpr message 
    printf "\n\033[0;31mERROR:\033[0m $1\n\n" >&2
    exit 1
}

if [[ $EUID -ne 0 ]]; then
    exit_error "This script must be run as root"
fi

OUTPUT_APT=$PWD/output_apt.txt
OUTPUT_SNAP=$PWD/output_snap.txt
OUTPUT_FLATPAK=$PWD/output_flatpak.txt

divider
print-output "Updating and upgrading apt packages"; INDENT=$?
apt-get -qq update > $OUTPUT_APT 2>&1; RETURN_STATUS_APT_1=$?
apt-get -y --allow-downgrades upgrade >> $OUTPUT_APT 2>&1 ; RETURN_STATUS_APT_2=$?

APT_RETURN=$((RETURN_STATUS_APT_1 + RETURN_STATUS_APT_2))

print-return $INDENT "$APT_RETURN"

if [ -x "$(command -v snap)" ]; then
    print-output "Updating snap packages"; INDENT=$?
    snap refresh > $OUTPUT_SNAP 2>&1; RETURN_STATUS_SNAP=$?
    print-return $INDENT $RETURN_STATUS_SNAP
fi

if [ -x "$(command -v flatpak)" ]; then
    print-output "Updating flatpak packages"; INDENT=$?
    flatpak update -y --noninteractive  >> $OUTPUT_FLATPAK 2>&1; RETURN_STATUS_FLATPAK=$?
    print-return $INDENT $RETURN_STATUS_FLATPAK
else
    ERROR_MESSAGE="Unable to locate Flatpak.";
    echo "$ERROR_MESSAGE" > $OUTPUT_FLATPAK
    print-output "${ERROR_MESSAGE}  Skipping..." ; INDENT=$?
    print-return $INDENT -1
    RETURN_STATUS_FLATPAK=1;
fi

if [ $APT_RETURN -ne 0 ]; then
    if [ $RETURN_STATUS_APT_1 -ne 0 ]; then
        print-output "Error updating apt packages"; INDENT=$?
        print-return $INDENT $RETURN_STATUS_APT_1
    fi
    if [ $RETURN_STATUS_APT_2 -ne 0 ]; then
        print-output "Error upgrading apt packages"; INDENT=$?
        print-return $INDENT $RETURN_STATUS_APT_2
    fi
    cat $OUTPUT_APT;
fi

if [ $RETURN_STATUS_SNAP -ne 0 ]; then
    print-output "Error updating snap packages"; INDENT=$?
    print-return $INDENT $RETURN_STATUS_SNAP
    cat $OUTPUT_SNAP;
fi

if [ $RETURN_STATUS_FLATPAK -ne 0 ]; then
    print-output "Error updating flatpak packages"; INDENT=$?
    print-return $INDENT $RETURN_STATUS_FLATPAK
    cat $OUTPUT_FLATPAK;
fi

rm $OUTPUT_SNAP
rm $OUTPUT_APT
rm $OUTPUT_FLATPAK

divider